
-- Drop the restrictive admin-only delete policy
DROP POLICY IF EXISTS "Admins delete transactions of their company" ON public.bank_transactions;

-- Admins can delete any transaction of their company
CREATE POLICY "Admins delete transactions of their company"
  ON public.bank_transactions
  FOR DELETE
  TO public
  USING (
    (company_id = get_user_company_id(auth.uid()))
    AND has_role(auth.uid(), 'admin'::app_role)
  );

-- Any user of the company can delete transactions generated by settlement (baixa)
-- from accounts_receivable or accounts_payable to allow cancellation
CREATE POLICY "Users delete own settlement transactions"
  ON public.bank_transactions
  FOR DELETE
  TO public
  USING (
    (company_id = get_user_company_id(auth.uid()))
    AND (origin_type IN ('contas_receber', 'contas_pagar'))
  );
